# ------------------------------------------------------------------------------
# FastAPI Movie
# ------------------------------------------------------------------------------
fastapi_movie:
  image: jhtyl13r/movie-fastapi
  containerPort: 8000
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    replicas: 1
# ------------------------------------------------------------------------------
# FastAPI Cast
# ------------------------------------------------------------------------------
fastapi_cast:
  image: jhtyl13r/cast-fastapi
  containerPort: 8000
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    replicas: 1
# ------------------------------------------------------------------------------
# Postgres Movie
# ------------------------------------------------------------------------------
postgres_movie:
  image: postgres:12.0-alpine
  port: 5432
  volumeSize: 1Gi
  replicas: 1
# ------------------------------------------------------------------------------
# Postgres Cast
# ------------------------------------------------------------------------------
postgres_cast:
  image: postgres:12.0-alpine
  port: 5432
  volumeSize: 1Gi
  replicas: 1
# ------------------------------------------------------------------------------
# NGINX
# ------------------------------------------------------------------------------
nginx:
  image: nginx:latest
  ports:
    containerPort: 8080

fastapi:
  movie:
    service:
      port: 8001
  cast:
    service:
      port: 8002


