# ------------------------------------------------------------------------------
# fastapi_cast
# ------------------------------------------------------------------------------
fastapi_cast:
  replicas: 1
# ------------------------------------------------------------------------------
# fastapi_movie
# ------------------------------------------------------------------------------
fastapi_movie:
  replicas: 1

# ------------------------------------------------------------------------------
# postgres_cast
# ------------------------------------------------------------------------------
postgres_cast:
  replicas: 1
  volumeSize: 1Gi
# ------------------------------------------------------------------------------
# postgres_movie
# ------------------------------------------------------------------------------
postgres_movie:
  replicas: 1
  volumeSize: 1Gi

# ------------------------------------------------------------------------------
# Nginx
# ------------------------------------------------------------------------------
nginx:
  ports:
    containerPort: 8080
  replicas: 1
  config: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://fastapi_movie_service:{{ .Values.fastapi.movie.service.port }}/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://fastapi_cast_service:{{ .Values.fastapi.cast.service.port }}/api/v1/casts;
      }
    }