apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres_movie.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres_movie.password }}
  POSTGRES_DB_MOVIE: {{ .Values.postgres_movie.db_movie }}
  POSTGRES_DB_CAST: {{ .Values.postgres_cast.db_cast }}
