# ------------------------------------------------------------------------------
# FastAPI Movie
# ------------------------------------------------------------------------------
fastapi_movie:
  image: jhtyl13r/movie-fastapi
  tag: "latest"
  containerPort: 8000
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    replicas: 1
    nodePort: 30020
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

# ------------------------------------------------------------------------------
# FastAPI Cast
# ------------------------------------------------------------------------------
fastapi_cast:
  image: jhtyl13r/cast-fastapi
  tag: "latest"
  containerPort: 8000
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    replicas: 1
    nodePort: 30021
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    ttargetCPUUtilizationPercentage: 70

# ------------------------------------------------------------------------------
# Postgres Movie
# ------------------------------------------------------------------------------
postgres_movie:
  image: postgres:12.0-alpine
  port: 5432
  volumeSize: 512Mi
  replicas: 1
# ------------------------------------------------------------------------------
# Postgres Cast
# ------------------------------------------------------------------------------
postgres_cast:
  image: postgres:12.0-alpine
  port: 5432
  volumeSize: 512Mi
  replicas: 1
# ------------------------------------------------------------------------------
# NGINX
# ------------------------------------------------------------------------------
nginx:
  image: nginx:latest
  ports:
    containerPort: 8080

fastapi:
  movie:
    service:
      port: 8001
  cast:
    service:
      port: 8002

# ------------------------------------------------------------------------------
# Ingress
# ------------------------------------------------------------------------------
ingress:
  name: fastapi-ingress
  ingressClassName: traefik
  host: devops.dev-euphony.fr
  path: /
  pathType: Prefix
  serviceName: fastapi-service
  servicePort: 80
  tls:
    - hosts:
        - devops.dev-euphony.fr
      secretName: mon-certificat-secret
